import React from 'react';
import { cn } from '~/utils';

export interface SessionFile {
  session_id: string;
  file_id: string;
  filename: string;
  generated_at?: string | Date;
}

/**
 * Phase 2 Task 4b — chip for files generated by the Code-Interpreter
 * (Conversation.session_files entries from Phase 3 Track 2).
 *
 * These files have NO db.files row — they live only as sub-documents on
 * the Conversation, surfaced to follow-up `/exec` calls via primeFiles.
 * The chip exists so users can see at a glance which files the agent has
 * produced and will reuse on the next code run.
 *
 * Schema is stable since Phase 3 Track 2 Task 8:
 *   { session_id, file_id, filename, generated_at }
 *
 * Tooltip carries `session_id` for debugging cross-session lineage.
 */
const SessionFileChip: React.FC<{ sessionFile: SessionFile }> = ({ sessionFile }) => {
  const tooltip = `${sessionFile.filename} (vom Code generiert · session ${sessionFile.session_id})`;
  return (
    <span
      className={cn('file-status-chip', 'chip-success')}
      title={tooltip}
      data-session-id={sessionFile.session_id}
    >
      📦 {sessionFile.filename} · vom Code generiert
    </span>
  );
};

export default SessionFileChip;
